-- Seed curatoriale iniziale (solo contenuti testuali/link)
-- Eseguire da SQL editor nel progetto Supabase.

insert into public.offerings (
  media_type,
  text_content,
  link_url,
  title,
  note,
  author_type,
  author_name,
  consent_rights,
  consent_archive,
  consent_reshare,
  status,
  submission_fingerprint,
  created_at
)
values
  (
    'text',
    'Un animale che non conosco, ma che mi riconosce.',
    null,
    'Senza nome',
    'Traccia breve.',
    'anonymous',
    null,
    true,
    true,
    false,
    'approved',
    'seed-curatoriale',
    now() - interval '9 days'
  ),
  (
    'text',
    'Per me Cavapendoli e quando una forma arriva prima della parola.',
    null,
    'Prima della parola',
    null,
    'name',
    'visitatrice',
    true,
    true,
    false,
    'approved',
    'seed-curatoriale',
    now() - interval '8 days'
  ),
  (
    'link',
    null,
    'https://example.com/eco',
    'Una eco trovata',
    'Link-segnaposto da sostituire.',
    'anonymous',
    null,
    true,
    true,
    false,
    'approved',
    'seed-curatoriale',
    now() - interval '7 days'
  ),
  (
    'text',
    'Cavapendoli e il rumore di una stanza vuota che respira.',
    null,
    'Stanza',
    null,
    'instagram',
    'ospite.traccia',
    true,
    true,
    false,
    'approved',
    'seed-curatoriale',
    now() - interval '6 days'
  ),
  (
    'text',
    'Una creatura utile a ricordare che non tutto va spiegato.',
    null,
    'Creatura utile',
    null,
    'anonymous',
    null,
    true,
    true,
    false,
    'approved',
    'seed-curatoriale',
    now() - interval '5 days'
  ),
  (
    'link',
    null,
    'https://example.com/soglia',
    'Soglia',
    'Link-segnaposto da sostituire.',
    'name',
    'ospite',
    true,
    true,
    false,
    'approved',
    'seed-curatoriale',
    now() - interval '4 days'
  ),
  (
    'text',
    'Per me significa lasciar parlare un simbolo prima di capirlo.',
    null,
    'Simbolo',
    null,
    'anonymous',
    null,
    true,
    true,
    false,
    'approved',
    'seed-curatoriale',
    now() - interval '3 days'
  ),
  (
    'text',
    'Un cavallo immaginario che non corre: ascolta.',
    null,
    'Ascolto',
    null,
    'name',
    'marta',
    true,
    true,
    false,
    'approved',
    'seed-curatoriale',
    now() - interval '2 days'
  ),
  (
    'text',
    'Una forma minima che ritorna quando serve coraggio.',
    null,
    'Coraggio minimo',
    null,
    'instagram',
    'traccia.minima',
    true,
    true,
    false,
    'approved',
    'seed-curatoriale',
    now() - interval '1 day'
  ),
  (
    'text',
    'Cavapendoli e un luogo da cui entrare senza fare rumore.',
    null,
    'Entrare piano',
    null,
    'anonymous',
    null,
    true,
    true,
    false,
    'approved',
    'seed-curatoriale',
    now() - interval '6 hours'
  );
